spring:

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: participant-service
              uri: lb://PARTICIPANT-SERVICE
              predicates:
                - Path=/api/v1/participants/**

            - id: event-service
              uri: lb://EVENT-SERVICE
              predicates:
                - Path=/api/v1/events/**

            - id: registration-service
              uri: lb://REGISTRATION-SERVICE
              predicates:
                - Path=/api/v1/registrations/**

          default-filters:
            - PreserveHostHeader

          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins: "*"
                allowed-methods: "*"
                allowed-headers: "*"
server:
  port: 7000